//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SGPS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class atendimentoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new atendimentoEntities object using the connection string found in the 'atendimentoEntities' section of the application configuration file.
        /// </summary>
        public atendimentoEntities() : base("name=atendimentoEntities", "atendimentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new atendimentoEntities object.
        /// </summary>
        public atendimentoEntities(string connectionString) : base(connectionString, "atendimentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new atendimentoEntities object.
        /// </summary>
        public atendimentoEntities(EntityConnection connection) : base(connection, "atendimentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<atendimento> atendimentoes
        {
            get
            {
                if ((_atendimentoes == null))
                {
                    _atendimentoes = base.CreateObjectSet<atendimento>("atendimentoes");
                }
                return _atendimentoes;
            }
        }
        private ObjectSet<atendimento> _atendimentoes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the atendimentoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToatendimentoes(atendimento atendimento)
        {
            base.AddObject("atendimentoes", atendimento);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="atendimentoModel", Name="atendimento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class atendimento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new atendimento object.
        /// </summary>
        /// <param name="idAtendimento">Initial value of the idAtendimento property.</param>
        /// <param name="idPaciente">Initial value of the idPaciente property.</param>
        /// <param name="strMotivoAtendimento">Initial value of the strMotivoAtendimento property.</param>
        /// <param name="strProvidencias">Initial value of the strProvidencias property.</param>
        /// <param name="idMaterial">Initial value of the idMaterial property.</param>
        /// <param name="dtmDataAtendimento">Initial value of the dtmDataAtendimento property.</param>
        public static atendimento Createatendimento(global::System.Int32 idAtendimento, global::System.Int32 idPaciente, global::System.String strMotivoAtendimento, global::System.String strProvidencias, global::System.Int32 idMaterial, global::System.DateTime dtmDataAtendimento)
        {
            atendimento atendimento = new atendimento();
            atendimento.idAtendimento = idAtendimento;
            atendimento.idPaciente = idPaciente;
            atendimento.strMotivoAtendimento = strMotivoAtendimento;
            atendimento.strProvidencias = strProvidencias;
            atendimento.idMaterial = idMaterial;
            atendimento.dtmDataAtendimento = dtmDataAtendimento;
            return atendimento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idAtendimento
        {
            get
            {
                return _idAtendimento;
            }
            set
            {
                if (_idAtendimento != value)
                {
                    OnidAtendimentoChanging(value);
                    ReportPropertyChanging("idAtendimento");
                    _idAtendimento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idAtendimento");
                    OnidAtendimentoChanged();
                }
            }
        }
        private global::System.Int32 _idAtendimento;
        partial void OnidAtendimentoChanging(global::System.Int32 value);
        partial void OnidAtendimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPaciente
        {
            get
            {
                return _idPaciente;
            }
            set
            {
                OnidPacienteChanging(value);
                ReportPropertyChanging("idPaciente");
                _idPaciente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idPaciente");
                OnidPacienteChanged();
            }
        }
        private global::System.Int32 _idPaciente;
        partial void OnidPacienteChanging(global::System.Int32 value);
        partial void OnidPacienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strMotivoAtendimento
        {
            get
            {
                return _strMotivoAtendimento;
            }
            set
            {
                OnstrMotivoAtendimentoChanging(value);
                ReportPropertyChanging("strMotivoAtendimento");
                _strMotivoAtendimento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strMotivoAtendimento");
                OnstrMotivoAtendimentoChanged();
            }
        }
        private global::System.String _strMotivoAtendimento;
        partial void OnstrMotivoAtendimentoChanging(global::System.String value);
        partial void OnstrMotivoAtendimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strProvidencias
        {
            get
            {
                return _strProvidencias;
            }
            set
            {
                OnstrProvidenciasChanging(value);
                ReportPropertyChanging("strProvidencias");
                _strProvidencias = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strProvidencias");
                OnstrProvidenciasChanged();
            }
        }
        private global::System.String _strProvidencias;
        partial void OnstrProvidenciasChanging(global::System.String value);
        partial void OnstrProvidenciasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMaterial
        {
            get
            {
                return _idMaterial;
            }
            set
            {
                OnidMaterialChanging(value);
                ReportPropertyChanging("idMaterial");
                _idMaterial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idMaterial");
                OnidMaterialChanged();
            }
        }
        private global::System.Int32 _idMaterial;
        partial void OnidMaterialChanging(global::System.Int32 value);
        partial void OnidMaterialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dtmDataAtendimento
        {
            get
            {
                return _dtmDataAtendimento;
            }
            set
            {
                OndtmDataAtendimentoChanging(value);
                ReportPropertyChanging("dtmDataAtendimento");
                _dtmDataAtendimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtmDataAtendimento");
                OndtmDataAtendimentoChanged();
            }
        }
        private global::System.DateTime _dtmDataAtendimento;
        partial void OndtmDataAtendimentoChanging(global::System.DateTime value);
        partial void OndtmDataAtendimentoChanged();

        #endregion
    
    }

    #endregion
    
}
