//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SGPS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class encaminhamentoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new encaminhamentoEntities object using the connection string found in the 'encaminhamentoEntities' section of the application configuration file.
        /// </summary>
        public encaminhamentoEntities() : base("name=encaminhamentoEntities", "encaminhamentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new encaminhamentoEntities object.
        /// </summary>
        public encaminhamentoEntities(string connectionString) : base(connectionString, "encaminhamentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new encaminhamentoEntities object.
        /// </summary>
        public encaminhamentoEntities(EntityConnection connection) : base(connection, "encaminhamentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<encaminhamento> encaminhamentoes
        {
            get
            {
                if ((_encaminhamentoes == null))
                {
                    _encaminhamentoes = base.CreateObjectSet<encaminhamento>("encaminhamentoes");
                }
                return _encaminhamentoes;
            }
        }
        private ObjectSet<encaminhamento> _encaminhamentoes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the encaminhamentoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToencaminhamentoes(encaminhamento encaminhamento)
        {
            base.AddObject("encaminhamentoes", encaminhamento);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sgpsModel", Name="encaminhamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class encaminhamento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new encaminhamento object.
        /// </summary>
        /// <param name="idEncaminhamento">Initial value of the idEncaminhamento property.</param>
        /// <param name="idPaciente">Initial value of the idPaciente property.</param>
        /// <param name="idHospital">Initial value of the idHospital property.</param>
        /// <param name="strMotivo">Initial value of the strMotivo property.</param>
        /// <param name="strSituacaoAtual">Initial value of the strSituacaoAtual property.</param>
        /// <param name="dtmDataEncaminhamento">Initial value of the dtmDataEncaminhamento property.</param>
        public static encaminhamento Createencaminhamento(global::System.Int32 idEncaminhamento, global::System.Int32 idPaciente, global::System.Int32 idHospital, global::System.String strMotivo, global::System.String strSituacaoAtual, global::System.DateTime dtmDataEncaminhamento)
        {
            encaminhamento encaminhamento = new encaminhamento();
            encaminhamento.idEncaminhamento = idEncaminhamento;
            encaminhamento.idPaciente = idPaciente;
            encaminhamento.idHospital = idHospital;
            encaminhamento.strMotivo = strMotivo;
            encaminhamento.strSituacaoAtual = strSituacaoAtual;
            encaminhamento.dtmDataEncaminhamento = dtmDataEncaminhamento;
            return encaminhamento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEncaminhamento
        {
            get
            {
                return _idEncaminhamento;
            }
            set
            {
                if (_idEncaminhamento != value)
                {
                    OnidEncaminhamentoChanging(value);
                    ReportPropertyChanging("idEncaminhamento");
                    _idEncaminhamento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEncaminhamento");
                    OnidEncaminhamentoChanged();
                }
            }
        }
        private global::System.Int32 _idEncaminhamento;
        partial void OnidEncaminhamentoChanging(global::System.Int32 value);
        partial void OnidEncaminhamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPaciente
        {
            get
            {
                return _idPaciente;
            }
            set
            {
                OnidPacienteChanging(value);
                ReportPropertyChanging("idPaciente");
                _idPaciente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idPaciente");
                OnidPacienteChanged();
            }
        }
        private global::System.Int32 _idPaciente;
        partial void OnidPacienteChanging(global::System.Int32 value);
        partial void OnidPacienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idHospital
        {
            get
            {
                return _idHospital;
            }
            set
            {
                OnidHospitalChanging(value);
                ReportPropertyChanging("idHospital");
                _idHospital = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idHospital");
                OnidHospitalChanged();
            }
        }
        private global::System.Int32 _idHospital;
        partial void OnidHospitalChanging(global::System.Int32 value);
        partial void OnidHospitalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strMotivo
        {
            get
            {
                return _strMotivo;
            }
            set
            {
                OnstrMotivoChanging(value);
                ReportPropertyChanging("strMotivo");
                _strMotivo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strMotivo");
                OnstrMotivoChanged();
            }
        }
        private global::System.String _strMotivo;
        partial void OnstrMotivoChanging(global::System.String value);
        partial void OnstrMotivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strSituacaoAtual
        {
            get
            {
                return _strSituacaoAtual;
            }
            set
            {
                OnstrSituacaoAtualChanging(value);
                ReportPropertyChanging("strSituacaoAtual");
                _strSituacaoAtual = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strSituacaoAtual");
                OnstrSituacaoAtualChanged();
            }
        }
        private global::System.String _strSituacaoAtual;
        partial void OnstrSituacaoAtualChanging(global::System.String value);
        partial void OnstrSituacaoAtualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dtmDataEncaminhamento
        {
            get
            {
                return _dtmDataEncaminhamento;
            }
            set
            {
                OndtmDataEncaminhamentoChanging(value);
                ReportPropertyChanging("dtmDataEncaminhamento");
                _dtmDataEncaminhamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtmDataEncaminhamento");
                OndtmDataEncaminhamentoChanged();
            }
        }
        private global::System.DateTime _dtmDataEncaminhamento;
        partial void OndtmDataEncaminhamentoChanging(global::System.DateTime value);
        partial void OndtmDataEncaminhamentoChanged();

        #endregion
    
    }

    #endregion
    
}
