//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SGPS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pacienteEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pacienteEntities object using the connection string found in the 'pacienteEntities' section of the application configuration file.
        /// </summary>
        public pacienteEntities() : base("name=pacienteEntities", "pacienteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pacienteEntities object.
        /// </summary>
        public pacienteEntities(string connectionString) : base(connectionString, "pacienteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pacienteEntities object.
        /// </summary>
        public pacienteEntities(EntityConnection connection) : base(connection, "pacienteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<paciente> pacientes
        {
            get
            {
                if ((_pacientes == null))
                {
                    _pacientes = base.CreateObjectSet<paciente>("pacientes");
                }
                return _pacientes;
            }
        }
        private ObjectSet<paciente> _pacientes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pacientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopacientes(paciente paciente)
        {
            base.AddObject("pacientes", paciente);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pacienteModel", Name="paciente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class paciente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new paciente object.
        /// </summary>
        /// <param name="idPaciente">Initial value of the idPaciente property.</param>
        /// <param name="strNome">Initial value of the strNome property.</param>
        /// <param name="strCategoria">Initial value of the strCategoria property.</param>
        /// <param name="strDataDeNascimento">Initial value of the strDataDeNascimento property.</param>
        /// <param name="strCpf">Initial value of the strCpf property.</param>
        /// <param name="strEndereco">Initial value of the strEndereco property.</param>
        /// <param name="strTelefone">Initial value of the strTelefone property.</param>
        public static paciente Createpaciente(global::System.Int32 idPaciente, global::System.String strNome, global::System.String strCategoria, global::System.String strDataDeNascimento, global::System.String strCpf, global::System.String strEndereco, global::System.String strTelefone)
        {
            paciente paciente = new paciente();
            paciente.idPaciente = idPaciente;
            paciente.strNome = strNome;
            paciente.strCategoria = strCategoria;
            paciente.strDataDeNascimento = strDataDeNascimento;
            paciente.strCpf = strCpf;
            paciente.strEndereco = strEndereco;
            paciente.strTelefone = strTelefone;
            return paciente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPaciente
        {
            get
            {
                return _idPaciente;
            }
            set
            {
                if (_idPaciente != value)
                {
                    OnidPacienteChanging(value);
                    ReportPropertyChanging("idPaciente");
                    _idPaciente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPaciente");
                    OnidPacienteChanged();
                }
            }
        }
        private global::System.Int32 _idPaciente;
        partial void OnidPacienteChanging(global::System.Int32 value);
        partial void OnidPacienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strNome
        {
            get
            {
                return _strNome;
            }
            set
            {
                OnstrNomeChanging(value);
                ReportPropertyChanging("strNome");
                _strNome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strNome");
                OnstrNomeChanged();
            }
        }
        private global::System.String _strNome;
        partial void OnstrNomeChanging(global::System.String value);
        partial void OnstrNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strCategoria
        {
            get
            {
                return _strCategoria;
            }
            set
            {
                OnstrCategoriaChanging(value);
                ReportPropertyChanging("strCategoria");
                _strCategoria = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strCategoria");
                OnstrCategoriaChanged();
            }
        }
        private global::System.String _strCategoria;
        partial void OnstrCategoriaChanging(global::System.String value);
        partial void OnstrCategoriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strDataDeNascimento
        {
            get
            {
                return _strDataDeNascimento;
            }
            set
            {
                OnstrDataDeNascimentoChanging(value);
                ReportPropertyChanging("strDataDeNascimento");
                _strDataDeNascimento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strDataDeNascimento");
                OnstrDataDeNascimentoChanged();
            }
        }
        private global::System.String _strDataDeNascimento;
        partial void OnstrDataDeNascimentoChanging(global::System.String value);
        partial void OnstrDataDeNascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strCpf
        {
            get
            {
                return _strCpf;
            }
            set
            {
                OnstrCpfChanging(value);
                ReportPropertyChanging("strCpf");
                _strCpf = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strCpf");
                OnstrCpfChanged();
            }
        }
        private global::System.String _strCpf;
        partial void OnstrCpfChanging(global::System.String value);
        partial void OnstrCpfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strEndereco
        {
            get
            {
                return _strEndereco;
            }
            set
            {
                OnstrEnderecoChanging(value);
                ReportPropertyChanging("strEndereco");
                _strEndereco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strEndereco");
                OnstrEnderecoChanged();
            }
        }
        private global::System.String _strEndereco;
        partial void OnstrEnderecoChanging(global::System.String value);
        partial void OnstrEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strTelefone
        {
            get
            {
                return _strTelefone;
            }
            set
            {
                OnstrTelefoneChanging(value);
                ReportPropertyChanging("strTelefone");
                _strTelefone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strTelefone");
                OnstrTelefoneChanged();
            }
        }
        private global::System.String _strTelefone;
        partial void OnstrTelefoneChanging(global::System.String value);
        partial void OnstrTelefoneChanged();

        #endregion
    
    }

    #endregion
    
}
