//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SGPS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class profissionalEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new profissionalEntities object using the connection string found in the 'profissionalEntities' section of the application configuration file.
        /// </summary>
        public profissionalEntities() : base("name=profissionalEntities", "profissionalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new profissionalEntities object.
        /// </summary>
        public profissionalEntities(string connectionString) : base(connectionString, "profissionalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new profissionalEntities object.
        /// </summary>
        public profissionalEntities(EntityConnection connection) : base(connection, "profissionalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<profissional> profissionals
        {
            get
            {
                if ((_profissionals == null))
                {
                    _profissionals = base.CreateObjectSet<profissional>("profissionals");
                }
                return _profissionals;
            }
        }
        private ObjectSet<profissional> _profissionals;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the profissionals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToprofissionals(profissional profissional)
        {
            base.AddObject("profissionals", profissional);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="profissionalModel", Name="profissional")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class profissional : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new profissional object.
        /// </summary>
        /// <param name="strNome">Initial value of the strNome property.</param>
        /// <param name="strCPF">Initial value of the strCPF property.</param>
        /// <param name="strCargo">Initial value of the strCargo property.</param>
        /// <param name="dtmHorario">Initial value of the dtmHorario property.</param>
        /// <param name="strEscala">Initial value of the strEscala property.</param>
        /// <param name="idProfissional">Initial value of the idProfissional property.</param>
        public static profissional Createprofissional(global::System.String strNome, global::System.String strCPF, global::System.String strCargo, global::System.DateTime dtmHorario, global::System.String strEscala, global::System.Int32 idProfissional)
        {
            profissional profissional = new profissional();
            profissional.strNome = strNome;
            profissional.strCPF = strCPF;
            profissional.strCargo = strCargo;
            profissional.dtmHorario = dtmHorario;
            profissional.strEscala = strEscala;
            profissional.idProfissional = idProfissional;
            return profissional;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strNome
        {
            get
            {
                return _strNome;
            }
            set
            {
                OnstrNomeChanging(value);
                ReportPropertyChanging("strNome");
                _strNome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strNome");
                OnstrNomeChanged();
            }
        }
        private global::System.String _strNome;
        partial void OnstrNomeChanging(global::System.String value);
        partial void OnstrNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strCPF
        {
            get
            {
                return _strCPF;
            }
            set
            {
                OnstrCPFChanging(value);
                ReportPropertyChanging("strCPF");
                _strCPF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strCPF");
                OnstrCPFChanged();
            }
        }
        private global::System.String _strCPF;
        partial void OnstrCPFChanging(global::System.String value);
        partial void OnstrCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strCargo
        {
            get
            {
                return _strCargo;
            }
            set
            {
                OnstrCargoChanging(value);
                ReportPropertyChanging("strCargo");
                _strCargo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strCargo");
                OnstrCargoChanged();
            }
        }
        private global::System.String _strCargo;
        partial void OnstrCargoChanging(global::System.String value);
        partial void OnstrCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dtmHorario
        {
            get
            {
                return _dtmHorario;
            }
            set
            {
                OndtmHorarioChanging(value);
                ReportPropertyChanging("dtmHorario");
                _dtmHorario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dtmHorario");
                OndtmHorarioChanged();
            }
        }
        private global::System.DateTime _dtmHorario;
        partial void OndtmHorarioChanging(global::System.DateTime value);
        partial void OndtmHorarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String strEscala
        {
            get
            {
                return _strEscala;
            }
            set
            {
                OnstrEscalaChanging(value);
                ReportPropertyChanging("strEscala");
                _strEscala = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("strEscala");
                OnstrEscalaChanged();
            }
        }
        private global::System.String _strEscala;
        partial void OnstrEscalaChanging(global::System.String value);
        partial void OnstrEscalaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProfissional
        {
            get
            {
                return _idProfissional;
            }
            set
            {
                if (_idProfissional != value)
                {
                    OnidProfissionalChanging(value);
                    ReportPropertyChanging("idProfissional");
                    _idProfissional = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idProfissional");
                    OnidProfissionalChanged();
                }
            }
        }
        private global::System.Int32 _idProfissional;
        partial void OnidProfissionalChanging(global::System.Int32 value);
        partial void OnidProfissionalChanged();

        #endregion
    
    }

    #endregion
    
}
